name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.5.1
homepage: https://github.com/rinukkusu/spotify-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0
  oauth2:
    git: git://github.com/dart-lang/oauth2.git
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.5.1
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
